# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np


arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)
arr1[:,2] = 1
print(arr1)


[[18 13 11  9  4]
 [11 15  2 11  6]
 [ 9 17  1 16 11]
 [16 16  9  6 16]
 [ 2  7 18 13  9]]
[[18 13  1  9  4]
 [11 15  1 11  6]
 [ 9 17  1 16 11]
 [16 16  1  6 16]
 [ 2  7  1 13  9]]


In [3]:
arr1_1 = np.random.randint(1,16,size=(4,4))
print("Original Array")
print(arr1_1)

print()

np.fill_diagonal(arr1_1,0)
print("Modified Array")
print(arr1_1)

Original Array
[[10  5 11 10]
 [ 2  5  9  4]
 [ 9 13  3  2]
 [ 4 15  7  4]]

Modified Array
[[ 0  5 11 10]
 [ 2  0  9  4]
 [ 9 13  0  2]
 [ 4 15  7  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
arr2 = np.random.randint(1,37, size=(6,6))
print(arr2)
print()
arr_temp = arr2[2:5,1:4]
print(arr_temp)

[[12 31  5 34 23 30]
 [23 36 30 14 27 33]
 [ 6 34 14 12 18  1]
 [13  7 33 22 33  1]
 [23 36 25 16 19  9]
 [23 15 14  3 31 24]]

[[34 14 12]
 [ 7 33 22]
 [36 25 16]]


In [5]:
arr2_2 = np.random.randint(1,21, size=(5,5))
border_elements = np.concatenate((arr2_2[0,:],arr2_2[-1,:],arr2_2[1:-1,0],arr2_2[1:-1,-1]))
print("Original Array")
print(arr2_2)
print("Border Elements")
print(border_elements)

Original Array
[[ 3 11 17 14  2]
 [ 7  5  1  8 19]
 [18 14 15  8 15]
 [20 13 10 14 14]
 [15 17 18  2  5]]
Border Elements
[ 3 11 17 14  2 15 17 18  2  5  7 18 20 19 15 14]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
arr3 = np.random.randint(1,12, size=(3,4))
arr3_1 = np.random.randint(1,12, size=(3,4))

print("Original First Array")
print(arr3)

print("Original Second Array")
print(arr3_1)

addition = arr3 + arr3_1
subtraction = arr3 - arr3_1
multiplication = arr3 * arr3_1
division = arr3 / arr3_1

print("Addition")
print(addition)
print("Subtraction")
print(subtraction)
print("Multiplication")
print(multiplication)
print("Division")
print(division)


Original First Array
[[10  4  1 11]
 [ 9  2  1 10]
 [ 7  9  9  9]]
Original Second Array
[[ 6 11  5  2]
 [10  2  4  9]
 [ 6  9  6  3]]
Addition
[[16 15  6 13]
 [19  4  5 19]
 [13 18 15 12]]
Subtraction
[[ 4 -7 -4  9]
 [-1  0 -3  1]
 [ 1  0  3  6]]
Multiplication
[[60 44  5 22]
 [90  4  4 90]
 [42 81 54 27]]
Division
[[1.66666667 0.36363636 0.2        5.5       ]
 [0.9        1.         0.25       1.11111111]
 [1.16666667 1.         1.5        3.        ]]


In [7]:
arr3_2 = np.random.randint(1,16,size=(4,4))

print("First Array:")
print(arr3_2)

print("Row wise sum: ")

for i in range(len(arr3_2)):
    row_wise_sum = 0
    for j in range(len(arr3_2[0])):
        row_wise_sum += arr3_2[i][j]
    print(f"Sum of {i}th Row : {row_wise_sum}")

print("Column wise sum: ")

for i in range(len(arr3_2[0])):
    col_wise_sum = 0
    for j in range(len(arr3_2)):
        col_wise_sum += arr3_2[j][i]
    print(f"Sum of {i}th Column : {col_wise_sum}")

First Array:
[[ 6 14 14  9]
 [ 4  3  1  3]
 [11 11  2  9]
 [ 2  8 10  6]]
Row wise sum: 
Sum of 0th Row : 43
Sum of 1th Row : 11
Sum of 2th Row : 33
Sum of 3th Row : 26
Column wise sum: 
Sum of 0th Column : 23
Sum of 1th Column : 36
Sum of 2th Column : 27
Sum of 3th Column : 27


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
arr4_1 = np.random.randint(1,25, size=(5,5))
print(arr4_1)
print(np.mean(arr4_1))
print(np.median(arr4_1))
print(np.std(arr4_1))
print(np.var(arr4_1))

[[16 14  2 13  4]
 [20  6 15  1 24]
 [16 10 19 24 23]
 [17 14  4 24 15]
 [21 18 17  3 17]]
14.28
16.0
7.090951981222267
50.2816


In [9]:
arr4_2 = np.arange(1,10).reshape((3,3))
print(arr4_2)
arr4_min = np.min(arr4_2)
arr4_max = np.max(arr4_2)

arr4_mean = np.mean(arr4_2)
arr4_std = np.std(arr4_2)
normalized_array = (arr4_2 - arr4_mean) / arr4_std
print("Normalized Array")
print(normalized_array)
print(np.mean(normalized_array))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr5_1 = np.random.randint(1,10, size=(3,3))
arr5_2 = np.random.randint(1,10, size=(3,))
print(arr5_1)
print(arr5_2)

arr5_rslt = arr5_1 + arr5_2

print(arr5_rslt)

[[4 7 1]
 [2 3 3]
 [6 8 9]]
[7 8 5]
[[11 15  6]
 [ 9 11  8]
 [13 16 14]]


In [ ]:
arr5_1 = np.random.randint(1,10, size=(4,4))
arr5_2 = np.random.randint(1,10, size=(4,))

print(arr5_1)
print(arr5_2)
# print(arr5_2[:, np.newaxis])
arr5_sub = arr5_1 - arr5_2[:, np.newaxis]
print(arr5_sub)

[[8 4 5 3]
 [7 2 7 5]
 [1 4 8 2]
 [2 9 7 3]]
[3 8 2 8]
[[3]
 [8]
 [2]
 [8]]
[[ 5  1  2  0]
 [-1 -6 -1 -3]
 [-1  2  6  0]
 [-6  1 -1 -5]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [26]:
arr6_1 = np.random.randint(1,10, size=(3,3))
print("Original array")
print(arr6_1)
print("Determinant")
print(np.linalg.det(arr6_1))
print("Inverse")
print(np.linalg.inv(arr6_1))
print("Eigenvalues")
print(np.linalg.eigvals(arr6_1))

Original array
[[7 2 3]
 [4 9 5]
 [9 5 1]]
Determinant
-213.00000000000009
Inverse
[[ 0.07511737 -0.06103286  0.07981221]
 [-0.19248826  0.09389671  0.10798122]
 [ 0.28638498  0.07981221 -0.25821596]]
Eigenvalues
[14.72797971  5.10498832 -2.83296803]


In [27]:
arr6_2 = np.random.randint(1,10, size=(2,3))
arr6_3 = np.random.randint(1,10, size=(3,2))

print(arr6_2)
print(arr6_3)
print("Result of matrix multiplication")
print(np.dot(arr6_2,arr6_3))

[[5 3 1]
 [9 1 1]]
[[6 8]
 [9 4]
 [7 3]]
Result of matrix multiplication
[[64 55]
 [70 79]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [33]:
arr7_1 = np.arange(1,10).reshape((3,3))
print("original array reshape(3,3)")
print(arr7_1)
print("reshaped array to (1,9)")
print(arr7_1.reshape(1,9))
print("reshaped again to (9,1)")
print(arr7_1.reshape(9,1))

original array reshape(3,3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
reshaped array to (1,9)
[[1 2 3 4 5 6 7 8 9]]
reshaped again to (9,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [37]:
arr7_2 = np.arange(1,26).reshape(5,5)
print("Original Array")
print(arr7_2)
print("Flattened Array")
arr7_flattend = arr7_2.flatten()
print(arr7_flattend)
print("Reshaped back to (5,5)")
arr7_reshaped = arr7_flattend.reshape(5,5)
print(arr7_reshaped)

Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Flattened Array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Reshaped back to (5,5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [41]:
arr8_1 = np.arange(1,26).reshape(5,5)
print("Original array : ")
print(arr8_1)
print("Elements at the corner of the array : ")
# array[ [rows], [columns] ]
arr8_corner = arr8_1[[0,0,-1,-1],[0,-1,0,-1]]
print(arr8_corner)


Original array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Elements at the corner of the array : 
[ 1  5 21 25]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.