# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np


arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)
arr1[:,2] = 1
print(arr1)


[[15 13 16 18  9]
 [19 16 16 10 13]
 [17 12  1  2 10]
 [ 3 19  4 19 18]
 [ 3  6  9  4  8]]
[[15 13  1 18  9]
 [19 16  1 10 13]
 [17 12  1  2 10]
 [ 3 19  1 19 18]
 [ 3  6  1  4  8]]


In [3]:
arr1_1 = np.random.randint(1,16,size=(4,4))
print("Original Array")
print(arr1_1)

print()

np.fill_diagonal(arr1_1,0)
print("Modified Array")
print(arr1_1)

Original Array
[[11 10  8  4]
 [ 1  8  1  7]
 [14 13 10  1]
 [11 11  4  6]]

Modified Array
[[ 0 10  8  4]
 [ 1  0  1  7]
 [14 13  0  1]
 [11 11  4  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
arr2 = np.random.randint(1,37, size=(6,6))
print(arr2)
print()
arr_temp = arr2[2:5,1:4]
print(arr_temp)

[[14  6  7 14 19 10]
 [24 19 36  3 32 14]
 [19 15 30 15 21 22]
 [11  1 29 29 18 15]
 [36 34  2 20 23 33]
 [ 2 36 14 16  4 31]]

[[15 30 15]
 [ 1 29 29]
 [34  2 20]]


In [5]:
arr2_2 = np.random.randint(1,21, size=(5,5))
border_elements = np.concatenate((arr2_2[0,:],arr2_2[-1,:],arr2_2[1:-1,0],arr2_2[1:-1,-1]))
print("Original Array")
print(arr2_2)
print("Border Elements")
print(border_elements)

Original Array
[[ 7 17 17 14  1]
 [ 9 13 18  3 12]
 [ 8 14  1 14 11]
 [ 3  4 18 11 14]
 [13  5 12  7 15]]
Border Elements
[ 7 17 17 14  1 13  5 12  7 15  9  8  3 12 11 14]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
arr3 = np.random.randint(1,12, size=(3,4))
arr3_1 = np.random.randint(1,12, size=(3,4))

print("Original First Array")
print(arr3)

print("Original Second Array")
print(arr3_1)

addition = arr3 + arr3_1
subtraction = arr3 - arr3_1
multiplication = arr3 * arr3_1
division = arr3 / arr3_1

print("Addition")
print(addition)
print("Subtraction")
print(subtraction)
print("Multiplication")
print(multiplication)
print("Division")
print(division)


Original First Array
[[ 8  4  9  5]
 [ 5  2  1  9]
 [10  2  7  7]]
Original Second Array
[[ 4  6  3  1]
 [ 8  2  4  4]
 [ 8  1  7 10]]
Addition
[[12 10 12  6]
 [13  4  5 13]
 [18  3 14 17]]
Subtraction
[[ 4 -2  6  4]
 [-3  0 -3  5]
 [ 2  1  0 -3]]
Multiplication
[[32 24 27  5]
 [40  4  4 36]
 [80  2 49 70]]
Division
[[2.         0.66666667 3.         5.        ]
 [0.625      1.         0.25       2.25      ]
 [1.25       2.         1.         0.7       ]]


In [7]:
arr3_2 = np.random.randint(1,16,size=(4,4))

print("First Array:")
print(arr3_2)

print("Row wise sum: ")

for i in range(len(arr3_2)):
    row_wise_sum = 0
    for j in range(len(arr3_2[0])):
        row_wise_sum += arr3_2[i][j]
    print(f"Sum of {i}th Row : {row_wise_sum}")

print("Column wise sum: ")

for i in range(len(arr3_2[0])):
    col_wise_sum = 0
    for j in range(len(arr3_2)):
        col_wise_sum += arr3_2[j][i]
    print(f"Sum of {i}th Column : {col_wise_sum}")

First Array:
[[12  2  8  5]
 [ 7  5 12  5]
 [ 7  1  1  7]
 [15 14 10  8]]
Row wise sum: 
Sum of 0th Row : 27
Sum of 1th Row : 29
Sum of 2th Row : 16
Sum of 3th Row : 47
Column wise sum: 
Sum of 0th Column : 41
Sum of 1th Column : 22
Sum of 2th Column : 31
Sum of 3th Column : 25


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
arr4_1 = np.random.randint(1,25, size=(5,5))
print(arr4_1)
print(np.mean(arr4_1))
print(np.median(arr4_1))
print(np.std(arr4_1))
print(np.var(arr4_1))

[[ 3 16 19  7  5]
 [ 6  3  7  5 17]
 [13 16 21 23 18]
 [21 11 10 18  3]
 [ 3 18 11  6 22]]
12.08
11.0
6.775957496915104
45.913599999999995


In [9]:
arr4_2 = np.arange(1,10).reshape((3,3))
print(arr4_2)
arr4_min = np.min(arr4_2)
arr4_max = np.max(arr4_2)

arr4_mean = np.mean(arr4_2)
arr4_std = np.std(arr4_2)
normalized_array = (arr4_2 - arr4_mean) / arr4_std
print("Normalized Array")
print(normalized_array)
print(np.mean(normalized_array))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [10]:
arr5_1 = np.random.randint(1,10, size=(3,3))
arr5_2 = np.random.randint(1,10, size=(3,))
print(arr5_1)
print(arr5_2)

arr5_rslt = arr5_1 + arr5_2

print(arr5_rslt)

[[7 4 8]
 [5 9 2]
 [4 3 7]]
[1 9 2]
[[ 8 13 10]
 [ 6 18  4]
 [ 5 12  9]]


In [11]:
arr5_1 = np.random.randint(1,10, size=(4,4))
arr5_2 = np.random.randint(1,10, size=(4,))

print(arr5_1)
print(arr5_2)
# print(arr5_2[:, np.newaxis])
arr5_sub = arr5_1 - arr5_2[:, np.newaxis]
print(arr5_sub)

[[8 6 5 6]
 [4 2 8 9]
 [1 8 4 6]
 [2 7 9 6]]
[2 8 2 9]
[[ 6  4  3  4]
 [-4 -6  0  1]
 [-1  6  2  4]
 [-7 -2  0 -3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [12]:
arr6_1 = np.random.randint(1,10, size=(3,3))
print("Original array")
print(arr6_1)
print("Determinant")
print(np.linalg.det(arr6_1))
print("Inverse")
print(np.linalg.inv(arr6_1))
print("Eigenvalues")
print(np.linalg.eigvals(arr6_1))

Original array
[[4 3 5]
 [4 8 9]
 [9 1 9]]
Determinant
46.99999999999999
Inverse
[[ 1.34042553 -0.46808511 -0.27659574]
 [ 0.95744681 -0.19148936 -0.34042553]
 [-1.44680851  0.4893617   0.42553191]]
Eigenvalues
[16.7494845   0.81733421  3.43318129]


In [13]:
arr6_2 = np.random.randint(1,10, size=(2,3))
arr6_3 = np.random.randint(1,10, size=(3,2))

print(arr6_2)
print(arr6_3)
print("Result of matrix multiplication")
print(np.dot(arr6_2,arr6_3))

[[6 3 5]
 [6 1 5]]
[[1 5]
 [1 3]
 [6 4]]
Result of matrix multiplication
[[39 59]
 [37 53]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [14]:
arr7_1 = np.arange(1,10).reshape((3,3))
print("original array reshape(3,3)")
print(arr7_1)
print("reshaped array to (1,9)")
print(arr7_1.reshape(1,9))
print("reshaped again to (9,1)")
print(arr7_1.reshape(9,1))

original array reshape(3,3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
reshaped array to (1,9)
[[1 2 3 4 5 6 7 8 9]]
reshaped again to (9,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [15]:
arr7_2 = np.arange(1,26).reshape(5,5)
print("Original Array")
print(arr7_2)
print("Flattened Array")
arr7_flattend = arr7_2.flatten()
print(arr7_flattend)
print("Reshaped back to (5,5)")
arr7_reshaped = arr7_flattend.reshape(5,5)
print(arr7_reshaped)

Original Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Flattened Array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Reshaped back to (5,5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [16]:
arr8_1 = np.arange(1,26).reshape(5,5)
print("Original array : ")
print(arr8_1)
print("Elements at the corner of the array : ")
# array[ [rows], [columns] ]
arr8_corner = arr8_1[[0,0,-1,-1],[0,-1,0,-1]]
print(arr8_corner)


Original array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Elements at the corner of the array : 
[ 1  5 21 25]


In [17]:
arr8_2 = np.random.randint(1,17, size=(4,4))
print("Original Array")
print(arr8_2)
print("Modified Array")
arr8_2[arr8_2 > 10] = 10
print(arr8_2)

Original Array
[[ 9 12  8  8]
 [16  4  5 16]
 [12  6  7  5]
 [13  1 16  6]]
Modified Array
[[ 9 10  8  8]
 [10  4  5 10]
 [10  6  7  5]
 [10  1 10  6]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [18]:
dtype = [('name','U10'),('age','i4'),('weight','f4')]
data = [('Rishabh',24,63),('Bob',35,78),('Alice',32,87)]

structured_array = np.array(data,dtype=dtype)
print("Structured Array")
print(structured_array)
sorted_array = np.sort(structured_array,order='age')
print(sorted_array)


Structured Array
[('Rishabh', 24, 63.) ('Bob', 35, 78.) ('Alice', 32, 87.)]
[('Rishabh', 24, 63.) ('Alice', 32, 87.) ('Bob', 35, 78.)]


In [19]:
dtype_2 = [('x','i4'),('y','i4')]
data_2 = [(1, 2), (3, 4), (5, 6)]

structured_array_2 = np.array(data_2,dtype=dtype_2)

distance_matrix = np.sqrt((structured_array_2['x'][:,np.newaxis] - structured_array_2['x'])**2 + (structured_array_2['y'][:,np.newaxis] - structured_array_2['y'])**2)

print(distance_matrix)


[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [20]:
import numpy.ma as ma

arr10 = np.random.randint(1,20, size=(4,4))

print("Original Array")
print(arr10)
# arr10[arr10 > 10] = 0
# print(arr10)
# print("Sum : ", np.sum(arr10))

print("Masked Array")
arr10_masked = ma.masked_greater(arr10,10)
print(arr10_masked)
print(f"Masked Array Sum : {ma.sum(arr10_masked)}")


Original Array
[[ 7 13  4 14]
 [ 8  5  1 19]
 [15 10  8 13]
 [ 9 15  8 10]]
Masked Array
[[7 -- 4 --]
 [8 5 1 --]
 [-- 10 8 --]
 [9 -- 8 10]]
Masked Array Sum : 70


In [26]:
arr10_2 = np.random.randint(1,10, size=(3,3))
arr10_2_masked = ma.masked_array(arr10_2,mask=np.eye(3,dtype=bool))
print("Original Array")
print(arr10_2)
print("Masked Array")
print(arr10_2_masked)
arr10_2_mean = np.mean(arr10_2)
print(f"Mean of Unmasked Array {arr10_2_mean}")
print("Modified Array")
arr10_modified = arr10_2_masked.filled(arr10_2_mean)
print(arr10_modified)

Original Array
[[1 7 9]
 [9 1 3]
 [5 5 2]]
Masked Array
[[-- 7 9]
 [9 -- 3]
 [5 5 --]]
Mean of Unmasked Array 4.666666666666667
Modified Array
[[4 7 9]
 [9 4 3]
 [5 5 4]]
